version: "3.9"

services:
  app:
    image: nextcloud:27
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - nextcloud-app-data:/var/www/html
    networks:
      - nextcloud-network
    environment:
      # database
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=db
      # admin account
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # object storage
      - OBJECTSTORE_S3_HOST=${OBJECTSTORE_S3_HOST}
      - OBJECTSTORE_S3_REGION=${OBJECTSTORE_S3_REGION}
      - OBJECTSTORE_S3_BUCKET=${OBJECTSTORE_S3_BUCKET}
      - OBJECTSTORE_S3_KEY=${OBJECTSTORE_S3_KEY}
      - OBJECTSTORE_S3_SECRET=${OBJECTSTORE_S3_SECRET}
      - OBJECTSTORE_S3_PORT=443
      - OBJECTSTORE_S3_SSL=true
      - OBJECTSTORE_S3_AUTOCREATE=true
      # - OBJECTSTORE_S3_USEPATH_STYLE=false
      # - OBJECTSTORE_S3_LEGACYAUTH=false
      # - OBJECTSTORE_S3_OBJECT_PREFIX=urn:oid:
      # redis
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - 13306:3306
    expose:
      - "13306"
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - nextcloud-network
    restart: always
  redis:
    image: redis:7.2
    ports:
      - 16379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - nextcloud-network
    restart: always

volumes:
  nextcloud-app-data:
    driver: local
  nextcloud-db-data:
    driver: local

networks:
  nextcloud-network:
    driver: bridge
